### ISSUE TITLE
address bar not updating after installing ms clarity on google tag manager

### ISSUE THREAD

**Issue by birkanbilici** [microsoft/clarity#152] opened 2021-07-12 12:45 UTC
Hi, ms clarity team. 

We recently started to have an issue with the address bar after our product owner has installed ms clarity on google tag manager by following the steps in the docs related to the installation of ms clarity from this [link](https://docs.microsoft.com/en-us/clarity/google-tag-manager).

The issue is currently observable by [visiting our page](https://www.apollo.de). The browser's address bar stops updating (continues to display the same address although it should change) after a few clicks (after two-three clicks...) on the top menu and category links expanding under the top menu items. 

We tracked the issue down to ms clarity after undertaking several tests. The issue is gone if we block ms clarity URL requests via network pane in developer tools through an adBlocker. 

We need a quick resolution or a recommendation since it is visible on our live page and we would like to continue using this product. It is probably negatively affecting our users and therefore our client's operation. Hoping to hear from you as soon as possible. 

Edit (update): In an attempt to find a workaround for this problem in our testing environment, I tried to override the history state with history.replace but I receive the error (please see attached image) coming from clarity after a few clicks because obviously clarity is trying to replace history too with history.replace (as evident from the error). We are using frontastic to serve our page. It handles all our routers. The issue seems to be connected to ms clarity script which is trying to change (replace) the history state. The workaround causes ms clarity to break with an error making the page no longer functional. Therefore, we are urgently expecting your recommendation, update, fix on the issue....

![Screen Shot 2021-07-15 at 14 13 27](https://user-images.githubusercontent.com/86365561/125779246-82e40995-59ae-4bf4-9c84-1ad71c0d652d.png)

(p.s. I am working as a front-end developer in the above-mentioned project's development team. We have also noticed a slowing down in the page's general operation after installation, which may or may not be related to this issue. Stalled URL state issue linking to ms clarity, verified with our tests, is of our higher priority at the moment.)

**Comment by sarveshnagpal** [comment] 2021-07-21 13:46
Thanks @birkanbilici for sharing the repro link. I've assigned it internally to the team and we will get back soon with an update.

**Comment by AbdelrhmanMagdy** [comment] 2024-09-10 10:46
Thanks for reporting this! I took a quick look but couldn't reproduce the issue. Given its age, it may have been fixed or is no longer relevant. If it persists in the latest version, feel free to reopen it or email us at [clarityms@microsoft.com](clarityms@microsoft.com) and provide more details.

**Closed by AbdelrhmanMagdy** 2024-09-10 10:46 UTC
