### ISSUE TITLE
Send custom ID's to clarity

### ISSUE THREAD

**Issue by OmriBenShoham** [microsoft/clarity#518] opened 2024-01-03 15:13 UTC
As part of our usage in Microsoft Clarity, we want to send our own IDs, for example: user_id, user_email.
We couldn't find a way to do so, this is our code:
```
import { clarity } from "clarity-js";

  const { user, isLoading } = useUser();

  useEffect(() => {
    if (!isLoading) {
      clarity.consent();

      if (user?.sub) {
        clarity.identify(user.sub, "", "", user.sub);
        clarity.set("user_id", user.sub);
      }

      if (user?.email) {
        clarity.set("user_email", user.email);
      }

      clarity.start({
        projectId: process.env.NEXT_PUBLIC_MICROSOFT_CLARITY,
        upload: "https://m.clarity.ms/collect",
        track: true,
        content: true,
      });
    }
    return () => {
      clarity.stop();
    };
  }, [user, isLoading]);
```

The variables I was trying to send from here are `user.sub`(our custom user id) and `user.email` which is our user email,
Please assist here what i'm missing in order to send those variables.

**Comment by GalDayan** [comment] 2024-01-04 07:16
👍

**Comment by Dbwani** [comment] 2024-01-06 11:06
I have been using Microsoft Clarity wordpress plugin from a long time. Few days ago, I installed the plugin on my new wordpress site namely [Toply10](https://www.toply10.com/). While google analytics is working finely on my site, but Microsoft Clarity plugin isn't showing up any realtime data especially in “Heatmap” section. I have already cleared all cache of my website many times, but still it shows some error like “Curl Error 7”. Is there anyone who can help me to sort out this problem?

Please note that I am using “Litespeed Cache“ plugin on my site. I feel like there arises some conflict between the two plugins. I have already reported to the microsoft clarity team.

Here is my website url: [my website - Toply10](https://www.toply10.com/)

**Comment by OmriBenShoham** [comment] 2024-01-09 16:48
Any help here?

**Comment by cyfyifanchen** [comment] 2024-02-18 05:35
@OmriBenShoham Have you seen this link? 

https://learn.microsoft.com/en-us/clarity/setup-and-installation/identify-api

**Comment by AbdelrhmanMagdy** [comment] 2024-03-20 14:44
Duplicate of #400.

**Closed by AbdelrhmanMagdy** 2024-03-20 14:44 UTC
