### ISSUE TITLE
Cannot read properties of null (reading 'sessionId')

### ISSUE THREAD

**Issue by SouthLink** [microsoft/clarity#656] opened 2024-08-26 06:12 UTC
If this is an issue you're seeing in https://clarity.microsoft.com please reach out to clarityms@microsoft.com with the details of your bug along with your project ID or a link to your project page.

---

For all other issues continue below:

Please also add all relevant labels from the list of existing ones. 

**Describe the bug**
clarity went crazy with errors on my production project (Cannot read properties of null (reading 'sessionId'))

**Repro Steps**
This introduces the SDK
```
function (id) {
  (function (c, l, a, r, i, t, y) {
    c[a] =
      c[a] ||
      function () {
        (c[a].q = c[a].q || []).push(arguments);
      };
    t = l.createElement(r);
    t.async = 1;
    t.src = "https://www.clarity.ms/tag/" + i;
    y = l.getElementsByTagName(r)[0];
    y.parentNode.insertBefore(t, y);
  })(window, document, "clarity", "script", id);
}

clarity("set", xx, xx);
 gtag("get", gtagId, key, (result: any) => {
       clarity("set", ga_session_id, result);
 });
```

**Screenshots**
![image](https://github.com/user-attachments/assets/2479e583-3d5a-40df-ae56-ec6752b31f07)

**Project info**
![image](https://github.com/user-attachments/assets/3fedbb52-ca41-48dd-b66e-7cf6c90e23bc)

**Browser info:**
![image](https://github.com/user-attachments/assets/7d636497-94f0-4eae-a531-8b1e561a9f75)

**Comment by ProsperBao** [comment] 2024-08-26 06:15
<img width="979" alt="image" src="https://github.com/user-attachments/assets/d4552fc2-aeb4-408a-8d49-55a850874503">

Yes, my sentry saw the same error

**Comment by abhieshekumar** [comment] 2024-08-26 07:20
We are also seeing a spike for the same issue since 0955 IST

**Comment by tomonari-t** [comment] 2024-08-26 09:00
We have started receiving similar errors reported by Sentry in our Rails web application as of today. It seems there are multiple types of error messages:

- `null is not an object (evaluating 'Qr.sessionId')`
- `TypeError: Cannot read properties of null (reading 'version')`
- `TypeError: null is not an object (evaluating 'yi.version')`

**Comment by gvillo** [comment] 2024-08-26 15:58
same here, getting all these errors starting today @ClaritySupport

**Comment by ClaritySupport** [comment] 2024-08-26 16:01
Hello,

Could you please share more details of the issue, project ID and website address along with link to the recordings having the issue to investigate further.


Thanks,
Clarity Support Team
Visit our docs!: https://docs.microsoft.com/en-us/clarity
***@***.******@***.***>
***@***.***

Confidentiality note: This e-mail, and any attachment to it, contains privileged and confidential information intended only for the use of the individual(s) or entity named in the e-mail.  If the reader of the e-mail is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that reading it is strictly prohibited.  If you have received this e-mail in error, please immediately return it to the sender and delete it from your system.

**Comment by abhieshekumar** [comment] 2024-08-26 16:16
Folks, maybe a naive question, what does this mean for the application? Does the break the user flow or simply prevents from recording analytics? 

@gvillo @SouthLink if you folks are aware? Unable to reproduce the issue 🙃

**Comment by ProsperBao** [comment] 2024-08-26 16:26
@abhieshekumar  It currently appears that there are no issues, both users and analytics are working fine, but the number of Sentry warnings has spiked, and we don't know if it might lead to additional problems. Therefore, our temporary solution here is to temporarily stop using it. I suspect that there might be some issues with certain nodes in the service. I am unable to reproduce the problem, and all the information I have comes from Sentry warnings.

**Comment by abhieshekumar** [comment] 2024-08-26 16:43
Thanks @ProsperBao

**Comment by ClaritySupport** [comment] 2024-08-26 18:50
Hello,

Could you please share more details of the issue, project ID and website address along with link to the recordings having the issue to investigate further.





Thanks,

Clarity Support Team

Visit our docs!: https://docs.microsoft.com/en-us/clarity

***@***.******@***.***>

[cid:3de91a1d-949a-45a7-b8f7-10e9356dfd9e]



Confidentiality note: This e-mail, and any attachment to it, contains privileged and confidential information intended only for the use of the individual(s) or entity named in the e-mail.  If the reader of the e-mail is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that reading it is strictly prohibited.  If you have received this e-mail in error, please immediately return it to the sender and delete it from your system.







________________________________

**Comment by ender336** [comment] 2024-08-28 21:52
@tomonari-t @ProsperBao @gvillo @SouthLink @abhieshekumar 

This seems to be a specific interaction between Sentry and Clarity, I haven't been able to reproduce it anywhere though. Couple questions to help me narrow it down:

* Did you see these errors before Clarity's version 0.7.45?
* Did you see these errors before August 25th when this issue was opened?
* Are the errors that Sentry is reporting specific to a browser or device? It looks like Southlink's image is just iOS but I'm not sure if that's where all of your traffic is, or if that's the only place this interaction is happening.

I suspect Sentry is somehow interfering with Clarity's ability to shut down in some cases - the errors all pasted here are indicative that our metadata module has cleaned itself up but something else is still trying to access its data.

**Comment by ProsperBao** [comment] 2024-08-29 01:40
It seems that this issue is not limited to version 0.7.45; I observed that it also occurred in version 0.7.41, albeit only once. Before August 25th, no similar problems were found, and it does not appear to be related to the browser.

<img width="944" alt="image" src="https://github.com/user-attachments/assets/580d2478-77e6-4282-ba39-32043cfb1298">

**Comment by tomonari-t** [comment] 2024-08-29 01:53
@ender336 Thank you for your replying.

My situation is same to @ProsperBao and @SouthLink.
These errors appeared between 12:30 on August 25 and 6:00 a.m on August 26, after which they disappeared.
So currently there is no errors.

**Comment by ender336** [comment] 2024-08-29 16:41
Thanks all, it must have been related to something our server was sending back in the /collect responses during that window. I'll focus around there. I'm going to close this issue as the issue is currently resolved - but please email clarityms@microsoft.com with your sites if it recures and include a link to this github issue so it can be routed to me quickly.

**Closed by ender336** 2024-08-29 16:41 UTC

**Comment by ProsperBao** [comment] 2024-09-02 15:07
@ender336  bro, the same problem has occurred again. My sentinel is issuing crazy warnings

**Comment by harshcut** [comment] 2024-09-02 16:27
Same here. Sentry is going crazy and Zenduty won't stop calling me 😭

**Comment by noboomu** [comment] 2024-09-02 22:06
Same. Can we reopen since it seems to be affecting multiple users? Sentry is showing the error is not handled which in many cases can break SPA. Here's the trace if it helps.

![image](https://github.com/user-attachments/assets/7a9b4056-2ce0-47a5-831b-da0ea3891ad1)

**Comment by SouthLink** [comment] 2024-09-03 01:12
![image](https://github.com/user-attachments/assets/be77fa2e-0756-4cd6-bfb3-ad3c6302059f)
This problem comes up again, crazy error reporting

**Comment by ahmadalfy** [comment] 2024-09-03 11:02
The problem is still happening
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/fef88c20-caf9-4eba-9a78-bfbeb6a514ef">

cc @sherifarmazhar

**Comment by davx1992** [comment] 2024-09-03 13:45
Yeah, same error for me as well.

**Comment by gvillo** [comment] 2024-09-03 18:46
Looks like it's only happening on NextJS apps, I have a vite react app and we are not getting those errors at all. I already sent an email to clarity about this. Let's see if they fix this!

**Comment by shaun-lawrie-ptml** [comment] 2024-09-03 22:31
Same the sdk not handling the error is bubbling up into the application using clarity and causing problems.

**Comment by ahmadalfy** [comment] 2024-09-04 08:26
> Looks like it's only happening on NextJS apps

Nope, happening in Nuxt as well

**Comment by Henrique0305** [comment] 2024-10-30 20:27
Any news related to these clarity Sentry related issues?
