### ISSUE TITLE
Page hangs on request to clarity api after last update to version 0.6.0

### ISSUE THREAD

**Issue by maxvin** [microsoft/clarity#78] opened 2020-12-21 12:21 UTC
After clarity was updated from 0.6.0-beta.22 to 0.6.0 we start to expect an issue on all our websites - in some cases all requests hangs in pending state and page became unresponsive. If clarity is disabled, either by removing integration or even if it just blocked in Chrome dev tools (by url) - all works good, without any issue.
We have angular 6 single page application.

**Comment by b4nghh** [comment] 2020-12-22 03:07
I also encountered this issue. I need to disable Clarity for now.
Please check the attachment for reference.

![Screenshot at Dec 22 10-05-26](https://user-images.githubusercontent.com/3040954/102844088-44a09300-443d-11eb-8a9f-dfe27f46f8ee.png)

**Comment by sarveshnagpal** [comment] 2020-12-22 04:35
Thanks @b4nghh for reporting. Issue from @maxvin is fixed in 0.6.1. It was due to how Zone.js overrode history APIs. From the stack trace above,  it looks like a different interaction - possibly with vue.js? Would you have a sample URL to share where I can repro the issue? It will help debug and resolve. Thanks.

**Comment by sarveshnagpal** [comment] 2020-12-22 19:05
Following up. Checked with @maxvin in a [separate conversation](https://github.com/microsoft/clarity/pull/77#issuecomment-749616548) that the issue is resolved with 0.6.1. 

@b4nghh - one possible way to get into that state (from screenshot above) would be to accidentally include script tag from clarity.microsoft.com on your page multiple times (more than once). Is it possible that this may be what's going on in this case? If you can ensure one instance is included - then things should work well with 0.6.1. Please feel free to open a new issue if this is not resolved. I'll close this one since the page hang issue is resolved.

**Closed by sarveshnagpal** 2020-12-22 19:05 UTC
